version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development

  frontend:
    build: ./resume-generator-client
    ports:
      - "80:80"
    depends_on:
      - backend
